import React from "react";

const AboutPage: React.FunctionComponent = () => {
  const [actionSheetOpened, setActionSheetOpened] = React.useState(false);

  return (
    <div className="page">
      <div className="section-container">
        <p>This mini app was generated by zmp-cli</p>
      </div>
      <div>
        <button
          onClick={() => setActionSheetOpened(true)}
          style={{ width: "100%", backgroundColor: "#f0f0f0" }} // Example styling
        >
          Show Action Sheet
        </button>
        {actionSheetOpened && (
          <div className="action-sheet">
            <p>This is the action sheet content.</p>
            <button onClick={() => setActionSheetOpened(false)}>Close</button>
          </div>
        )}
      </div>
    </div>
  );
};

export default AboutPage;
